[package]
name = "tdm"
version = "0.1.0"
edition = "2018"


[[bin]]
name = "tdm"
doc = false

[dependencies]
serde_yaml = "0.8"
serde = {version = "1.0", features = ["derive"]}
xdg = "2.2"
chrono = "0.4"
rand = "0.8"
